### ISSUE TITLE
Limit size of tabs

### ISSUE THREAD

**Issue by adnbsr** [iammert/ReadableBottomBar#1]
When there are many tabs lets say 10 of them, tabs become non-readable since textview ellipsized text.

Should bottombar be scrollable horizontally?

**Comment by iammert** [comment]
I will add scrollable feature asap.

**Comment by adnbsr** [comment]
After creating issue, I checked  `BottomNavigationView` source. Indeed, there was a max limit for menuitem count. 

https://android.googlesource.com/platform/frameworks/support/+/9253a923d5de1336a385775b23cac04680a0af2a/design/src/android/support/design/internal/BottomNavigationMenu.java#28
