### ISSUE TITLE
Setting initial index Programatically

### ISSUE THREAD

**Issue by aadit33** [iammert/ReadableBottomBar#2]
How to set initial index programmatically or what i want is that On backpress on want to got to initial index

**Comment by roiacult** [comment]
i hade the same problem so i forkted and implemented setSelecetdItem methode 
check my fork its can help you

**Comment by iammert** [comment]
Fixed. https://github.com/iammert/ReadableBottomBar/commit/ca43916305d34fb5952656beaecce7d6e87c3474 use version 0.2
